### PR TITLE
fixes #171 Swift 4.2 Support and #172 Example app layout lacks support for iPhone X

### LINKED ISSUE #171: Swift 4.2 Support
The project should be converted using Xcode "Edit -> Convert -> to Current Swift Syntax..." feature.

I will submit a PR in a couple of minutes.

### PR DESCRIPTION
**Pull request by rolandkakonyi**

### CODE REVIEW

**Comment by iamcam** [comment]
@rolandkakonyi The README probably also needs to be updated to reflect some type changes.

**Comment by rolandkakonyi** [comment]
@iamcam I updated the README, pls review.
I wasn't sure about the `cameraManager.stopVideoRecording` call as I didn't use that before.

Note: I didn't increase the version of the pod as this is something that the maintainers should decide if this is a major or minor version change.

**Comment by rolandkakonyi** [comment]
@iamcam Please check this if still needed, thx

**Comment by MortMerr** [comment]
What about merging it?

**Comment by gamafranco** [comment]
Sorry, we need to test it first. Give us a few days to get it done properly.

**Comment by gamafranco** [comment]
Argh. Was hopping to be able to get this done, but we have our hands tied ATM with projects.

If someone can conduct QA on this, we'll accept the merge request. Otherwise we need to be able to get our hands on the code and test it properly before merging.

**Comment by MortMerr** [comment]
@gamafranco any updates?

**Comment by Daxito** [comment]
+1

**Comment by sashk1n** [comment]
+1

**Comment by jweg29** [comment]
Any updates would be greatly appreciated @gamafranco  🙂

**Comment by gamafranco** [comment]
...big apologies for leaving it like this. Give us a couple of days and it will be out. This time is for real. Thanks.

**Pull request merged**
